services:
  db:
    image: mysql
    healthcheck:
      test: [ "CMD", "ls" ]
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: product_management_system
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - databaseVolume:/var/lib/mysql
    networks:
      - appNetwork
  backend:
    image: budcoded/productmanagementsystem:latest
    ports:
      - "1111:1111"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/product_management_system
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: app_password
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL5Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy
    networks:
      - appNetwork
    volumes:
      - logsVolume:/logs
  frontend:
    image: budcoded/productmanagementsystemui:latest
    networks:
      - appNetwork
    ports:
      - "3000:3000"
volumes:
  databaseVolume:
  logsVolume:
networks:
  appNetwork: